/**
 * RevivePay - Synthetic Demo Data Seeder
 * 
 * NOTE: All records generated by this script are SYNTHETIC DEMO DATA
 * created specifically for the Razorpay AI Buildathon (Revenue Recovery Track).
 * Absolutely NO real customer, card, or live transaction data is contained herein.
 */

import { PrismaClient, FailureReason, RecoveryStrategy } from '@prisma/client';

const prisma = new PrismaClient();

const MERCHANTS_DATA = [
  {
    name: 'SaaSify Cloud Technologies',
    email: 'billing@saasifycloud.io',
    policy: {
      max_retries: 3,
      max_discount_pct: 15.0,
      high_value_approval_threshold: 50000.0,
    },
  },
  {
    name: 'Aura Lifestyle & Apparel',
    email: 'finance@auralifestyle.in',
    policy: {
      max_retries: 3,
      max_discount_pct: 20.0,
      high_value_approval_threshold: 30000.0,
    },
  },
  {
    name: 'QuickBite Logistics & Food',
    email: 'payments@quickbitedeliver.com',
    policy: {
      max_retries: 4,
      max_discount_pct: 10.0,
      high_value_approval_threshold: 40000.0,
    },
  },
];

const FIRST_NAMES = [
  'Aarav', 'Aditi', 'Rohan', 'Priya', 'Vikram', 'Neha', 'Kabir', 'Ananya',
  'Rahul', 'Pooja', 'Siddharth', 'Tanvi', 'Arjun', 'Meera', 'Dev', 'Kavita',
  'Kunal', 'Simran', 'Ishaan', 'Rhea', 'Manish', 'Shreya', 'Amit', 'Divya',
  'Deepak', 'Nisha', 'Alok', 'Sneha', 'Gaurav', 'Tara', 'Sunil', 'Swati',
  'Varun', 'Pallavi', 'Naveen', 'Isha', 'Harsh', 'Sonal', 'Rajesh', 'Preeti',
];

const LAST_NAMES = [
  'Sharma', 'Verma', 'Patel', 'Iyer', 'Reddy', 'Mehta', 'Nair', 'Kapoor',
  'Gupta', 'Singh', 'Bose', 'Chopra', 'Joshi', 'Malhotra', 'Deshmukh', 'Saxena',
  'Kulkarni', 'Bhatia', 'Menon', 'Rao',
];

const PAYMENT_METHODS = ['card', 'upi', 'netbanking'];

const FAILURE_REASONS: FailureReason[] = [
  FailureReason.NETWORK_ERROR,
  FailureReason.INSUFFICIENT_FUNDS,
  FailureReason.BANK_ERROR,
  FailureReason.AUTHENTICATION_FAILED,
  FailureReason.CARD_DECLINED,
  FailureReason.EXPIRED_CARD,
];

// Weighted selection for failure reasons
function getWeightedFailureReason(): FailureReason {
  const rand = Math.random();
  if (rand < 0.28) return FailureReason.NETWORK_ERROR;
  if (rand < 0.55) return FailureReason.INSUFFICIENT_FUNDS;
  if (rand < 0.75) return FailureReason.BANK_ERROR;
  if (rand < 0.88) return FailureReason.AUTHENTICATION_FAILED;
  if (rand < 0.96) return FailureReason.CARD_DECLINED;
  return FailureReason.EXPIRED_CARD;
}

function getRandomDateWithinDays(days: number): Date {
  const now = Date.now();
  const past = now - days * 24 * 60 * 60 * 1000;
  const randomTime = past + Math.random() * (now - past);
  return new Date(randomTime);
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

async function main() {
  console.log('🌱 Starting RevivePay synthetic demo data seed...');

  // Clean existing tables in reverse order of foreign keys
  await prisma.auditLog.deleteMany();
  await prisma.recoveryOutcome.deleteMany();
  await prisma.intervention.deleteMany();
  await prisma.agentAction.deleteMany();
  await prisma.recoveryPrediction.deleteMany();
  await prisma.failedPayment.deleteMany();
  await prisma.paymentAttempt.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.customer.deleteMany();
  await prisma.merchantPolicy.deleteMany();
  await prisma.merchant.deleteMany();

  console.log('🧹 Cleaned existing database records.');

  let totalMerchants = 0;
  let totalCustomers = 0;
  let totalPayments = 0;
  let totalFailedPayments = 0;

  for (const mData of MERCHANTS_DATA) {
    // 1. Create Merchant
    const merchant = await prisma.merchant.create({
      data: {
        name: mData.name,
        email: mData.email,
        policy: {
          create: {
            max_retries: mData.policy.max_retries,
            max_discount_pct: mData.policy.max_discount_pct,
            high_value_approval_threshold: mData.policy.high_value_approval_threshold,
          },
        },
      },
    });
    totalMerchants++;

    // 2. Create 40 Customers per merchant
    const createdCustomers = [];
    for (let cIdx = 0; cIdx < 40; cIdx++) {
      const firstName = FIRST_NAMES[cIdx % FIRST_NAMES.length];
      const lastName = LAST_NAMES[(cIdx + totalMerchants * 5) % LAST_NAMES.length];
      const fullName = `${firstName} ${lastName}`;
      const emailDomain = mData.name.toLowerCase().includes('saas') ? 'company.com' : 'gmail.com';
      const email = `${firstName.toLowerCase()}.${lastName.toLowerCase()}${cIdx + 1}@${emailDomain}`;
      const phone = `+91 98${randomInt(10000000, 99999999)}`;

      // Diverse customer profile distributions
      const isVip = cIdx < 8;
      const isAtRisk = cIdx >= 32;

      const successfulPaymentsCount = isVip
        ? randomInt(25, 60)
        : isAtRisk
        ? randomInt(1, 8)
        : randomInt(8, 24);

      const failedPaymentsCount = isVip
        ? randomInt(1, 4)
        : isAtRisk
        ? randomInt(4, 12)
        : randomInt(2, 6);

      const ltv = isVip
        ? parseFloat((randomInt(60000, 200000)).toFixed(2))
        : isAtRisk
        ? parseFloat((randomInt(2000, 15000)).toFixed(2))
        : parseFloat((randomInt(15000, 55000)).toFixed(2));

      const recoveryRate = isVip
        ? parseFloat((0.75 + Math.random() * 0.20).toFixed(2))
        : isAtRisk
        ? parseFloat((0.15 + Math.random() * 0.25).toFixed(2))
        : parseFloat((0.45 + Math.random() * 0.30).toFixed(2));

      const customer = await prisma.customer.create({
        data: {
          merchant_id: merchant.id,
          name: fullName,
          email,
          phone,
          lifetime_value: ltv,
          successful_payments: successfulPaymentsCount,
          failed_payments: failedPaymentsCount,
          historical_recovery_rate: recoveryRate,
        },
      });
      createdCustomers.push(customer);
      totalCustomers++;
    }

    // 3. Create 160 Payments per merchant (~30% failed)
    const paymentsToGenerate = 160;
    for (let pIdx = 0; pIdx < paymentsToGenerate; pIdx++) {
      const customer = createdCustomers[pIdx % createdCustomers.length];
      const paymentDate = getRandomDateWithinDays(14);
      const isFailed = pIdx % 10 < 3; // Exactly 30% failure rate (3 out of every 10)

      // Mix of standard amounts and occasional high-value transactions
      const isHighValue = Math.random() < 0.08;
      const amount = isHighValue
        ? parseFloat((randomInt(52000, 95000)).toFixed(2))
        : parseFloat((randomInt(499, 14999)).toFixed(2));

      const method = PAYMENT_METHODS[pIdx % PAYMENT_METHODS.length];

      const payment = await prisma.payment.create({
        data: {
          merchant_id: merchant.id,
          customer_id: customer.id,
          amount,
          currency: 'INR',
          status: isFailed ? 'FAILED' : 'SUCCESS',
          method,
          created_at: paymentDate,
          updated_at: paymentDate,
        },
      });
      totalPayments++;

      if (isFailed) {
        totalFailedPayments++;
        const reason = getWeightedFailureReason();
        const retryCount = Math.random() < 0.65 ? 0 : Math.random() < 0.85 ? 1 : 2;

        // Create Payment Attempts
        for (let a = 1; a <= retryCount + 1; a++) {
          await prisma.paymentAttempt.create({
            data: {
              payment_id: payment.id,
              attempt_number: a,
              status: 'FAILED',
              error_message: `Gateway failure: ${reason}`,
              attempted_at: new Date(paymentDate.getTime() + (a - 1) * 3600000),
            },
          });
        }

        // Create Failed Payment
        await prisma.failedPayment.create({
          data: {
            payment_id: payment.id,
            failure_reason: reason,
            retry_count: retryCount,
            status: 'UNRESOLVED',
            failed_at: paymentDate,
          },
        });
      } else {
        // Success payment attempt
        await prisma.paymentAttempt.create({
          data: {
            payment_id: payment.id,
            attempt_number: 1,
            status: 'SUCCESS',
            error_message: null,
            attempted_at: paymentDate,
          },
        });
      }
    }
  }

  console.log('✅ Synthetic Demo Data Seeding Completed Successfully!');
  console.log(`--------------------------------------------------`);
  console.log(`📊 Summary of Generated Synthetic Data:`);
  console.log(`   - Merchants:        ${totalMerchants}`);
  console.log(`   - MerchantPolicies: ${totalMerchants}`);
  console.log(`   - Customers:        ${totalCustomers} (40 per merchant)`);
  console.log(`   - Payments:         ${totalPayments} (160 per merchant)`);
  console.log(`   - Failed Payments:  ${totalFailedPayments} (~${Math.round((totalFailedPayments / totalPayments) * 100)}% failure rate)`);
  console.log(`--------------------------------------------------`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
